# UV Configuration - Single Environment Setup
[project]
name = "energy"
requires-python = ">=3.8"

[tool.uv]
python = "3.11"
system = false
compile = true
seed = true

[tool.uv.pip]
index-url = "https://pypi.org/simple"
pre = false
no-cache = false

[tool.uv.venv]
prompt = "energy"
system-site-packages = false

# Parallel processing for package installation
[tool.uv.parallel]
enabled = true
jobs = 4
