@startuml data_driven_engineering
skinparam titleBorderRoundCorner 15
skinparam titleBorderThickness 2
skinparam titleBorderColor red
skinparam titleBackgroundColor Tomato

title Data Driven Engineering & Manufacturing \nMeasurement & Metrics

    participant Proposal
    participant "Design Data" as dd
    participant Design
    participant Engineering
    participant Manufacturing
    participant Deliverables
    activate Proposal

    activate Proposal
    activate dd
    activate Engineering
    activate Manufacturing
    activate Deliverables

    alt Project management 
        Proposal-> Deliverables: End to end management \n (eg. Jira)
    end group

    alt Data Management 
        Proposal-> Deliverables: Data Repository as Single source of truth for project \n (eg. database or ascii files)
    end group

    alt Data Gathering
        Proposal-> Deliverables: Utilize hub & APIs
    end group

note over dd
    - Mature design data within timeframe 
    - Parametrize the unknowns
    - Perform sensitivity analysis to finailize unknowns & \n get approval
end note


note over Design
    <b>Phase 1
    - Use data repo
    - assembly drawings & animations
    <b>Phase 2
    - Program, fit-up, assembly sequences
    - Automate drawings
end note


note over Engineering
    <b>Phase 1
    - Use data repo
    - Utilize design models for analysis
    <b>Phase 2
    - Parametric analysis
    - Document more than required results
end note


note over Manufacturing
    <b>Phase 1 Process: Code generation
    - Automate machine scripts
    <b>Phase 2 Process: Code automation
    - Send scripts by API calls based on PM tasks
end note

note over Manufacturing
    <b>Phase 1 Machine Metrics: Descriptive
    - Tasks completed
    - Human resources required
    <b>Phase 2 Machine Metrics: Predictive
    - IoT device data
    - Predict failures for critical machinery
end note


footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

@enduml