@startgantt
scale 4
Project starts the 2021/11/24
[Splashtop Access] lasts 0 days and is colored in Coral
[Update RAO and sanity checks] starts 0 day after [Splashtop Access]'s end  and lasts 2 days and is colored in Lavender/LightBlue
[Update model]  starts 0 day after [Update RAO and sanity checks]'s end and lasts 4 days and is colored in Lavender/LightBlue
[Preliminary Results]  starts 0 day after [Update model]'s end and lasts 2 days and is colored in Lavender/LightBlue
[Final Results] starts 0 day after [Preliminary Results]'s end and lasts 2 days and is colored in Lavender/LightBlue
[Upstream/Downstream (not in scope)] starts 0 day after [Final Results]'s end and lasts 2 days and is colored in Lavender/LightBlue
@endgantt