@startuml

title Project workflow process

state "Idle Queue" as Idle
[*] -> Idle
Idle -> Queue : Task Arrives
Queue : Task placed in queue.
Queue -> Worker : Worker collects Task
Worker -> DRev

state "Di Review (1 Week)" as DRev {
  [*] --> long1
  long1 --> ProcessData : Enough Data
}

DRev -> [*]

@enduml
