@startuml project_process_workflow
start
:Project Lead;
partition ProjectLead_Go_Decision {

note
    Project Acceptance: 
    Go (or) No Go in 5 business days
    Mature Requirements
    Mature Estimates
    Responsibility: Vamsee A., Patrick T.
end note

:Meeting to mature requirements;
:Finalize requirements in XOM ADO;
:Estimate by Disys TaaS Lead;
:Review req/estimates by Client;

}

:Work Project acceptance;

partition Each-Project-WorkCycle {

note
    Work Project Execution:
    Agile sync with client
    Responsibility: Disys Lead, Developer
    Measurement: Story points vs. workdays
end note

:Onboard project;
:TaaS Lead sync with agile sprint cycles
with XOM (lead/product owner)
Review/change story points as required;
: Accept additional work
Stories, features with story points;
:Product Acceptance by Client
User, Feature, Work Project Close-out;

}

:Get feedback;
:Project close-out;

stop
@enduml