@startwbs
* Project Organization
** Procure project work
*** Person 1
*** Person 2
** US Resources
*** Technical Project Manager
*** Doc Controller/BA
** Project Resources
*** Project manager (scrum master/planning/release train)
*** 2 Fullstack developers
*** 1 Devops/Automation
*** 1 PowerBI + SQL
*** 1 Scrum master + release train
@endwbs