apiVersion: v1
kind: Service
metadata:
  name: nexus-dynacard-k8-service
spec:
  selector:
    app: dynacard-flask
  ports:
  - protocol: "TCP"
    port: 5007
    targetPort: 5005
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynacard-flask
spec:
  selector:
    matchLabels:
      app: dynacard-flask
  replicas: 2
  template:
    metadata:
      labels:
        app: dynacard-flask
    spec:
      containers:
      - name: dynacard-flask
        image: dynacard-flask:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5005