@startwbs
title FEED \n Project Structure 

footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

* Project Manager

** Document Controller \n Support 
*** Templates 
*** Document review & approval
*** Meeting Minutes
*** Budget & Schedule
*** Project management tool (Jira etc.)

** Lead | Wellhead Platform 
*** Sr. Global Analyst
*** Global Analyst
*** SACS/ANSYS analyst 1
*** SACS/ANSYS analyst 2
*** Engineer MTO (50%)
*** Drawings Designer 1 (50%)
*** Geotech Resource (50%)
*** Specs SME 1 (40%)

** Lead | SURF
*** Process Analyst
*** Drawings Designer 1 (50%)
*** Specs SME 1 (30%)

** Lead | Company Documentation
*** Technical Writer


** Lead | FPSO
*** Process Analyst
*** Mechanical & Piping Designer
*** Top side & Turret interface SME/Analyst
*** Engineer MTO (50%)
*** Drawings Designer 1 (100%)
*** Drawings Designer 2 (100%)
*** Specs SME 1 (30%)


@endwbs