@startwbs
title FEED \n Project Structure 

footer
%date("yyyy.MM.dd' at 'HH:mm")
%filename()
end footer

* Project Manager \n Facilities Engineer \n QA/HSE Manager \n  Field Layout & development Engineer \n Mechanical-Lead cum Static Eqpmnt \n Mechanical-Rotating equipment


** Document Controller \n Support 
*** Procurement Manager (Lead)
*** Procurement Officer
*** Project Control Lead
*** Document controller cum Secretary



** Lead | Wellhead Platform 
*** Sr. Global Analyst
*** Global Analyst
*** SACS/ANSYS analyst 1
*** SACS/ANSYS analyst 2
*** Engineer MTO (50%)
*** Drawings Designer 1 (50%)
*** Geotech Resource (50%)
*** Specs SME 1 (40%)

** Lead | SURF
*** Process Analyst
*** Drawings Designer 1 (50%)
*** Specs SME 1 (30%)

** Lead | Company Documentation
*** Technical Writer

** Lead | FPSO
*** Hull & Mooring engineer
*** Naval Architect
*** Process Analyst
*** E&I Lead
*** Mechanical & Piping Designer
*** Top side & Turret interface SME/Analyst
*** Engineer MTO (50%)
*** Drawings Designer 1 (100%)
*** Drawings Designer 2 (100%)
*** Specs SME 1 (30%)

@endwbs