name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    
    - name: Install uv
      uses: astral-sh/setup-uv@v4
    
    - name: Update dependencies
      run: |
        if [ -f "pyproject.toml" ]; then
          echo "Updating Python dependencies..."
          uv pip compile pyproject.toml --upgrade || true
        fi
        if [ -f "requirements.txt" ]; then
          echo "Updating requirements.txt dependencies..."
          uv pip compile requirements.txt --upgrade || true
        fi
    
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: "chore: update dependencies"
        title: "Automated dependency updates"
        body: |
          This PR contains automated dependency updates.
          
          - Updated Python package versions
          - Resolved compatibility issues
          
          Please review the changes before merging.
        branch: dependency-updates
        delete-branch: true